[llm]
openai_api_key = "${OPENAI_API_KEY}"
model_name = "gpt-4.1-nano"
temperature = 0.1
max_tokens = 2000

[agent_defaults]
max_iterations = 3
max_execution_time = 30.0
handle_parsing_errors = true

[logging]
level = "INFO"
format = "json"
structured = true

[strategy_generation]
timeout_seconds = 10
max_retries = 2
fallback_enabled = true

[prompts.strategy]
system_message = "You are an expert email communication strategist."
temperature = 0.7
max_tokens = 1500
