version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "universal-framework-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "universal-framework-team"
