# config.yaml

model_list:
  - model_name: claude-3-opus-20240229
    litellm_params:
      model: qwen3-coder-480b-a35b-instruct
      api_key: os.environ/ANTHROPIC_AUTH_TOKEN
      api_base: https://dashscope-intl.aliyuncs.com/compatible-mode/v1

# General settings for the proxy server
litellm_settings:
  drop_params: True # This prevents errors by dropping unsupported parameters